/*!
 * sly 1.3.0 - 30th Nov 2014
 * https://github.com/darsain/sly
 *
 * Licensed under the MIT license.
 * http://opensource.org/licenses/MIT
 */
(function(k,M,Ka){function ma(g,n,A){var ha,l,ua,r,M,na,va,oa;function ea(){if(e.initialized){var a=0,c=v.length;f.old=k.extend({},f);y=I?0:C[b.horizontal?"width":"height"]();T=J[b.horizontal?"width":"height"]();t=I?g:u[b.horizontal?"outerWidth":"outerHeight"]();v.length=0;f.start=0;f.end=db(t-y,0);if(D){a=m.length;G=u.children(b.itemSelector);m.length=0;var d=pa(u,b.horizontal?"paddingLeft":"paddingTop"),wa=pa(u,b.horizontal?"paddingRight":"paddingBottom"),n="border-box"===k(G).css("boxSizing"),
A="none"!==G.css("float"),p=0,r=G.length-1,q;t=0;G.each(function(a,c){var e=k(c),f=e[b.horizontal?"outerWidth":"outerHeight"](),g=pa(e,b.horizontal?"marginLeft":"marginTop"),e=pa(e,b.horizontal?"marginRight":"marginBottom"),h=f+g+e,n=!g||!e,l={};l.el=c;l.size=n?f:h;l.half=l.size/2;l.start=t+(n?g:0);l.center=l.start-z(y/2-l.size/2);l.end=l.start-y+l.size;a||(t+=d);t+=h;b.horizontal||A||e&&g&&0<a&&(t-=La(g,e));a===r&&(l.end+=wa,t+=wa,p=n?e:0);m.push(l);q=l});u[0].style[b.horizontal?"width":"height"]=
(n?t:t-d-wa)+"px";t-=p;m.length?(f.start=m[0][U?"center":"start"],f.end=U?q.center:y<t?q.end:f.start):f.start=f.end=0}f.center=z(f.end/2+f.start/2);k.extend(h,xa(void 0));E.length&&0<T&&(b.dynamicHandle?(N=f.start===f.end?T:z(T*y/t),N=F(N,b.minHandleSize,T),E[0].style[b.horizontal?"width":"height"]=N+"px"):N=E[b.horizontal?"outerWidth":"outerHeight"](),w.end=T-N,V||Ma());if(!I&&0<y){var l=f.start,n="";if(D)k.each(m,function(a,c){U?v.push(c.center):c.start+c.size>l&&l<=f.end&&(l=c.start,v.push(l),
l+=y,l>f.end&&l<f.end+y&&v.push(f.end))});else for(;l-y<f.end;)v.push(l),l+=y;if(W[0]&&c!==v.length){for(c=0;c<v.length;c++)n+=b.pageBuilder.call(e,c);ja=W.html(n).children();ja.eq(h.activePage).addClass(b.activeClass)}}h.slideeSize=t;h.frameSize=y;h.sbSize=T;h.handleSize=N;D?(e.initialized?(h.activeItem>=m.length||0===a&&0<m.length)&&qa(h.activeItem>=m.length?m.length-1:0,!a):(qa(b.startAt),e[L?"toCenter":"toStart"](b.startAt)),a=m[h.activeItem],K(L&&a?a.center:F(f.dest,f.start,f.end))):e.initialized?
K(F(f.dest,f.start,f.end)):K(b.startAt,1);B("load")}}function K(a,c,ia){if(D&&d.released&&!ia){ia=xa(a);var g=a>f.start&&a<f.end;L?(g&&(a=m[ia.centerItem].center),U&&b.activateMiddle&&qa(ia.centerItem)):g&&(a=m[ia.firstItem].start)}d.init&&d.slidee&&b.elasticBounds?a>f.end?a=f.end+(a-f.end)/6:a<f.start&&(a=f.start+(a-f.start)/6):a=F(a,f.start,f.end);ha=+new Date;l=0;ua=f.cur;r=a;M=a-f.cur;na=d.tweese||d.init&&!d.slidee;va=!na&&(c||d.init&&d.slidee||!b.speed);d.tweese=0;a!==f.dest&&(f.dest=a,B("change"),
V||ya());d.released&&!e.isPaused&&e.resume();k.extend(h,xa(void 0));Na();ja[0]&&p.page!==h.activePage&&(p.page=h.activePage,ja.removeClass(b.activeClass).eq(h.activePage).addClass(b.activeClass),B("activePage",p.page))}function ya(){e.initialized&&(V?(va?f.cur=r:na?(oa=r-f.cur,.1>X(oa)?f.cur=r:f.cur+=oa*(d.released?b.swingSpeed:b.syncSpeed)):(l=La(+new Date-ha,b.speed),f.cur=ua+M*jQuery.easing[b.easing](l/b.speed,l,0,1,b.speed)),r===f.cur?(f.cur=r,d.tweese=V=0):V=ra(ya),B("move"),I||(O?u[0].style[O]=
ka+(b.horizontal?"translateX":"translateY")+"("+-f.cur+"px)":u[0].style[b.horizontal?"left":"top"]=-z(f.cur)+"px"),!V&&d.released&&B("moveEnd"),Ma()):(V=ra(ya),d.released&&B("moveStart")))}function Ma(){E.length&&(w.cur=f.start===f.end?0:((d.init&&!d.slidee?f.dest:f.cur)-f.start)/(f.end-f.start)*w.end,w.cur=F(z(w.cur),w.start,w.end),p.hPos!==w.cur&&(p.hPos=w.cur,O?E[0].style[O]=ka+(b.horizontal?"translateX":"translateY")+"("+w.cur+"px)":E[0].style[b.horizontal?"left":"top"]=w.cur+"px"))}function Oa(){x.speed&&
f.cur!==(0<x.speed?f.end:f.start)||e.stop();Pa=d.init?ra(Oa):0;x.now=+new Date;x.pos=f.cur+(x.now-x.lastTime)/1E3*x.speed;K(d.init?x.pos:z(x.pos));d.init||f.cur!==f.dest||B("moveEnd");x.lastTime=x.now}function za(a,c,b){"boolean"===la(c)&&(b=c,c=Ka);c===Ka?K(f[a],b):L&&"center"!==a||(c=e.getPos(c))&&K(c[a],b,!L)}function sa(a){return null!=a?P(a)?0<=a&&a<m.length?a:-1:G.index(a):-1}function Aa(a){return sa(P(a)&&0>a?a+m.length:a)}function qa(a,c){var d=sa(a);if(!D||0>d)return!1;if(p.active!==d||c)G.eq(h.activeItem).removeClass(b.activeClass),
G.eq(d).addClass(b.activeClass),p.active=h.activeItem=d,Na(),B("active",d);return d}function xa(a){a=F(P(a)?a:f.dest,f.start,f.end);var c={},d=U?0:y/2;if(!I)for(var b=0,e=v.length;b<e;b++){if(a>=f.end||b===v.length-1){c.activePage=v.length-1;break}if(a<=v[b]+d){c.activePage=b;break}}if(D){for(var e=b=d=!1,g=0,h=m.length;g<h;g++)if(!1===d&&a<=m[g].start+m[g].half&&(d=g),!1===e&&a<=m[g].center+m[g].half&&(e=g),g===h-1||a<=m[g].end+m[g].half){b=g;break}c.firstItem=P(d)?d:0;c.centerItem=P(e)?e:c.firstItem;
c.lastItem=P(b)?b:c.centerItem}return c}function Na(){var a=f.dest<=f.start,c=f.dest>=f.end,e=a?1:c?2:3;p.slideePosState!==e&&(p.slideePosState=e,Y.is("button,input")&&Y.prop("disabled",a),Z.is("button,input")&&Z.prop("disabled",c),Y.add(fa)[a?"addClass":"removeClass"](b.disabledClass),Z.add(aa)[c?"addClass":"removeClass"](b.disabledClass));p.fwdbwdState!==e&&d.released&&(p.fwdbwdState=e,fa.is("button,input")&&fa.prop("disabled",a),aa.is("button,input")&&aa.prop("disabled",c));D&&(a=0===h.activeItem,
c=h.activeItem>=m.length-1,e=a?1:c?2:3,p.itemsButtonState!==e&&(p.itemsButtonState=e,ba.is("button,input")&&ba.prop("disabled",a),ca.is("button,input")&&ca.prop("disabled",c),ba[a?"addClass":"removeClass"](b.disabledClass),ca[c?"addClass":"removeClass"](b.disabledClass)))}function Qa(a,c,e){a=Aa(a);c=Aa(c);if(-1<a&&-1<c&&a!==c&&(!e||c!==a-1)&&(e||c!==a+1)){G.eq(a)[e?"insertAfter":"insertBefore"](m[c].el);var b=a<c?a:e?c:c-1,d=a>c?a:e?c+1:c,f=a>c;a===h.activeItem?p.active=h.activeItem=e?f?c+1:c:f?
c:c-1:h.activeItem>b&&h.activeItem<d&&(p.active=h.activeItem+=f?1:-1);ea()}}function Ra(a,c){for(var e=0,b=H[a].length;e<b;e++)if(H[a][e]===c)return e;return-1}function Sa(a){return z(F(a,w.start,w.end)/w.end*(f.end-f.start))+f.start}function eb(){d.history[0]=d.history[1];d.history[1]=d.history[2];d.history[2]=d.history[3];d.history[3]=d.delta}function Ta(a){d.released=0;d.source=a;d.slidee="slidee"===a}function Ua(a){var c="touchstart"===a.type,g=a.data.source,h="slidee"===g;d.init||!c&&Va(a.target)||
!("handle"!==g||b.dragHandle&&w.start!==w.end)||!(!h||(c?b.touchDragging:b.mouseDragging&&2>a.which))||(c||Q(a),Ta(g),d.init=0,d.$source=k(a.target),d.touch=c,d.pointer=c?a.originalEvent.touches[0]:a,d.initX=d.pointer.pageX,d.initY=d.pointer.pageY,d.initPos=h?f.cur:w.cur,d.start=+new Date,d.time=0,d.path=0,d.delta=0,d.locked=0,d.history=[0,0,0,0],d.pathToLock=h?c?30:10:0,da.on(c?"touchmove.sly touchend.sly":"mousemove.sly mouseup.sly",Wa),e.pause(1),(h?u:E).addClass(b.draggedClass),B("moveStart"),
h&&(Xa=setInterval(eb,10)))}function Wa(a){d.released="mouseup"===a.type||"touchend"===a.type;d.pointer=d.touch?a.originalEvent[d.released?"changedTouches":"touches"][0]:a;d.pathX=d.pointer.pageX-d.initX;d.pathY=d.pointer.pageY-d.initY;d.path=fb(Ya(d.pathX,2)+Ya(d.pathY,2));d.delta=b.horizontal?d.pathX:d.pathY;if(!d.init)if(b.horizontal?X(d.pathX)>X(d.pathY):X(d.pathX)<X(d.pathY))d.init=1;else return Za();Q(a);!d.locked&&d.path>d.pathToLock&&d.slidee&&(d.locked=1,d.$source.on("click.sly",Ba));d.released&&
(Za(),b.releaseSwing&&d.slidee&&(d.swing=(d.delta-d.history[0])/40*300,d.delta+=d.swing,d.tweese=10<X(d.swing)));K(d.slidee?z(d.initPos-d.delta):Sa(d.initPos+d.delta))}function Za(){clearInterval(Xa);da.off(d.touch?"touchmove.sly touchend.sly":"mousemove.sly mouseup.sly",Wa);(d.slidee?u:E).removeClass(b.draggedClass);setTimeout(function(){d.$source.off("click.sly",Ba)});e.resume(1);f.cur===f.dest&&d.init&&B("moveEnd");d.init=0}function Va(a){return~k.inArray(a.nodeName,gb)||k(a).is(b.interactive)}
function $a(){e.stop();da.off("mouseup",$a)}function ga(a){Q(a);switch(this){case aa[0]:case fa[0]:e.moveBy(aa.is(this)?b.moveBy:-b.moveBy);da.on("mouseup",$a);break;case ba[0]:e.prev();break;case ca[0]:e.next();break;case Y[0]:e.prevPage();break;case Z[0]:e.nextPage()}}function hb(a){var c=+new Date;Ca+300>c?Ca=c:b.scrollBy&&f.start!==f.end&&(c=a.originalEvent,q.curDelta=(b.horizontal?c.deltaY||c.deltaX:c.deltaY)||-c.wheelDelta,q.curDelta/=1===c.deltaMode?3:100,D?(Da=+new Date,q.last<Da-q.resetTime&&
(q.delta=0),q.last=Da,q.delta+=q.curDelta,1>X(q.delta)?q.finalDelta=0:(q.finalDelta=z(q.delta/1),q.delta%=1),c=q.finalDelta):c=q.curDelta,(b.scrollTrap||0<c&&f.dest<f.end||0>c&&f.dest>f.start)&&Q(a,1),e.slideBy(b.scrollBy*c))}function ib(a){b.clickBar&&a.target===J[0]&&(Q(a),K(Sa((b.horizontal?a.pageX-J.offset().left:a.pageY-J.offset().top)-N/2)))}function jb(a){if(b.keyboardNavBy)switch(a.which){case b.horizontal?37:38:Q(a);e["pages"===b.keyboardNavBy?"prevPage":"prev"]();break;case b.horizontal?
39:40:Q(a),e["pages"===b.keyboardNavBy?"nextPage":"next"]()}}function kb(a){Va(this)?a.stopPropagation():this.parentNode===u[0]&&e.activate(this)}function lb(){this.parentNode===W[0]&&e.activatePage(ja.index(this))}function mb(a){if(b.pauseOnHover)e["mouseenter"===a.type?"pause":"resume"](2)}function B(a,c){if(H[a]){Ea=H[a].length;for(R=Fa.length=0;R<Ea;R++)Fa.push(H[a][R]);for(R=0;R<Ea;R++)Fa[R].call(e,a,c)}}var b=k.extend({},ma.defaults,n),e=this,I=P(g),C=k(g),u=C.children().eq(0),y=0,t=0,f={start:0,
center:0,end:0,cur:0,dest:0},J=k(b.scrollBar).eq(0),E=J.children().eq(0),T=0,N=0,w={start:0,end:0,cur:0},W=k(b.pagesBar),ja=0,v=[],G=0,m=[],h={firstItem:0,lastItem:0,centerItem:0,activeItem:-1,activePage:0},Ga=new ta(C[0]),Ha=new ta(u[0]),Ia=new ta(J[0]),Ja=new ta(E[0]);n="basic"===b.itemNav;var U="forceCentered"===b.itemNav,L="centered"===b.itemNav||U,D=!I&&(n||L||U),ab=b.scrollSource?k(b.scrollSource):C,nb=b.dragSource?k(b.dragSource):C,aa=k(b.forward),fa=k(b.backward),ba=k(b.prev),ca=k(b.next),
Y=k(b.prevPage),Z=k(b.nextPage),H={},p={};oa=va=na=M=r=ua=l=ha=void 0;var x={},d={released:1},q={last:0,delta:0,resetTime:200},V=0,Xa=0,S=0,Pa=0,R,Ea;I||(g=C[0]);e.initialized=0;e.frame=g;e.slidee=u[0];e.pos=f;e.rel=h;e.items=m;e.pages=v;e.isPaused=0;e.options=b;e.dragging=d;e.reload=ea;e.getPos=function(a){if(D)return a=sa(a),-1!==a?m[a]:!1;var c=u.find(a).eq(0);return c[0]?(a=b.horizontal?c.offset().left-u.offset().left:c.offset().top-u.offset().top,c=c[b.horizontal?"outerWidth":"outerHeight"](),
{start:a,center:a-y/2+c/2,end:a-y+c,size:c}):!1};e.moveBy=function(a){x.speed=a;!d.init&&x.speed&&f.cur!==(0<x.speed?f.end:f.start)&&(x.lastTime=+new Date,x.startPos=f.cur,Ta("button"),d.init=1,B("moveStart"),bb(Pa),Oa())};e.stop=function(){"button"===d.source&&(d.init=0,d.released=1)};e.prev=function(){e.activate(h.activeItem-1)};e.next=function(){e.activate(h.activeItem+1)};e.prevPage=function(){e.activatePage(h.activePage-1)};e.nextPage=function(){e.activatePage(h.activePage+1)};e.slideBy=function(a,
c){if(a)if(D)e[L?"toCenter":"toStart"](F((L?h.centerItem:h.firstItem)+b.scrollBy*a,0,m.length));else K(f.dest+a,c)};e.slideTo=function(a,c){K(a,c)};e.toStart=function(a,c){za("start",a,c)};e.toEnd=function(a,c){za("end",a,c)};e.toCenter=function(a,c){za("center",a,c)};e.getIndex=sa;e.activate=function(a,c){var f=qa(a);b.smart&&!1!==f&&(L?e.toCenter(f,c):f>=h.lastItem?e.toStart(f,c):f<=h.firstItem?e.toEnd(f,c):d.released&&!e.isPaused&&e.resume())};e.activatePage=function(a,c){P(a)&&K(v[F(a,0,v.length-
1)],c)};e.resume=function(a){!b.cycleBy||!b.cycleInterval||"items"===b.cycleBy&&!m[0]||a<e.isPaused||(e.isPaused=0,S?S=clearTimeout(S):B("resume"),S=setTimeout(function(){B("cycle");switch(b.cycleBy){case "items":e.activate(h.activeItem>=m.length-1?0:h.activeItem+1);break;case "pages":e.activatePage(h.activePage>=v.length-1?0:h.activePage+1)}},b.cycleInterval))};e.pause=function(a){a<e.isPaused||(e.isPaused=a||100,S&&(S=clearTimeout(S),B("pause")))};e.toggle=function(){e[S?"pause":"resume"]()};e.set=
function(a,c){k.isPlainObject(a)?k.extend(b,a):b.hasOwnProperty(a)&&(b[a]=c)};e.add=function(a,c){var e=k(a);D?(null==c||!m[0]||c>=m.length?e.appendTo(u):m.length&&e.insertBefore(m[c].el),c<=h.activeItem&&(p.active=h.activeItem+=e.length)):u.append(e);ea()};e.remove=function(a){if(D){if(a=Aa(a),-1<a){G.eq(a).remove();var c=a===h.activeItem;a<h.activeItem&&(p.active=--h.activeItem);ea();c&&(p.active=null,e.activate(h.activeItem))}}else k(a).remove(),ea()};e.moveAfter=function(a,c){Qa(a,c,1)};e.moveBefore=
function(a,c){Qa(a,c)};e.on=function(a,c){if("object"===la(a))for(var b in a){if(a.hasOwnProperty(b))e.on(b,a[b])}else if("function"===la(c)){b=a.split(" ");for(var d=0,f=b.length;d<f;d++)H[b[d]]=H[b[d]]||[],-1===Ra(b[d],c)&&H[b[d]].push(c)}else if("array"===la(c))for(b=0,d=c.length;b<d;b++)e.on(a,c[b])};e.one=function(a,c){function b(){c.apply(e,arguments);e.off(a,b)}e.on(a,b)};e.off=function(a,c){if(c instanceof Array)for(var b=0,d=c.length;b<d;b++)e.off(a,c[b]);else for(var b=a.split(" "),d=0,
f=b.length;d<f;d++)if(H[b[d]]=H[b[d]]||[],null==c)H[b[d]].length=0;else{var g=Ra(b[d],c);-1!==g&&H[b[d]].splice(g,1)}};e.destroy=function(){da.add(ab).add(E).add(J).add(W).add(aa).add(fa).add(ba).add(ca).add(Y).add(Z).unbind(".sly");ba.add(ca).add(Y).add(Z).removeClass(b.disabledClass);G&&G.eq(h.activeItem).removeClass(b.activeClass);W.empty();I||(C.unbind(".sly"),Ga.restore(),Ha.restore(),Ia.restore(),Ja.restore(),k.removeData(g,"sly"));m.length=v.length=0;p={};e.initialized=0;return e};e.init=function(){if(!e.initialized){e.on(A);
var a=["overflow","position"],c="position webkitTransform msTransform transform left top width height".split(" ");Ga.save.apply(Ga,a);Ia.save.apply(Ia,a);Ha.save.apply(Ha,c);Ja.save.apply(Ja,c);a=E;I||(a=a.add(u),C.css("overflow","hidden"),O||"static"!==C.css("position")||C.css("position","relative"));O?ka&&a.css(O,ka):("static"===J.css("position")&&J.css("position","relative"),a.css({position:"absolute"}));if(b.forward)aa.on("mousedown.sly",ga);if(b.backward)fa.on("mousedown.sly",ga);if(b.prev)ba.on("click.sly",
ga);if(b.next)ca.on("click.sly",ga);if(b.prevPage)Y.on("click.sly",ga);if(b.nextPage)Z.on("click.sly",ga);ab.on(cb,hb);if(J[0])J.on("click.sly",ib);if(D&&b.activateOn)C.on(b.activateOn+".sly","*",kb);if(W[0]&&b.activatePageOn)W.on(b.activatePageOn+".sly","*",lb);nb.on("touchstart.sly mousedown.sly",{source:"slidee"},Ua);if(E)E.on("touchstart.sly mousedown.sly",{source:"handle"},Ua);da.bind("keydown.sly",jb);I||(C.on("mouseenter.sly mouseleave.sly",mb),C.on("scroll.sly",ob));e.initialized=1;ea();if(b.cycleBy&&
!I)e[b.startPaused?"pause":"resume"]();return e}}}function la(g){return null==g?String(g):"object"===typeof g||"function"===typeof g?Object.prototype.toString.call(g).match(/\s([a-z]+)/i)[1].toLowerCase()||"object":typeof g}function Q(g,n){g.preventDefault();n&&g.stopPropagation()}function Ba(g){Q(g,1);k(this).off(g.type,Ba)}function ob(){this.scrollTop=this.scrollLeft=0}function P(g){return!isNaN(parseFloat(g))&&isFinite(g)}function pa(g,n){return 0|z(String(g.css(n)).replace(/[^\-0-9.]/g,""))}function F(g,
n,k){return g<n?n:g>k?k:g}function ta(g){var n={style:{},save:function(){if(g){for(var k=0;k<arguments.length;k++)n.style[arguments[k]]=g.style[arguments[k]];return n}},restore:function(){if(g){for(var k in n.style)n.style.hasOwnProperty(k)&&(g.style[k]=n.style[k]);return n}}};return n}var bb=M.cancelAnimationFrame||M.cancelRequestAnimationFrame,ra=M.requestAnimationFrame,O,ka,da=k(document),cb=(document.implementation.hasFeature("Event.wheel","3.0")?"wheel.":"mousewheel.")+"sly",gb=["INPUT","SELECT",
"BUTTON","TEXTAREA"],Fa=[],Da,X=Math.abs,fb=Math.sqrt,Ya=Math.pow,z=Math.round,db=Math.max,La=Math.min,Ca=0;da.on(cb,function(){Ca=+new Date});(function(g){function k(g){var n=(new Date).getTime(),r=Math.max(0,16-(n-A));g=setTimeout(g,r);A=n;return g}ra=g.requestAnimationFrame||g.webkitRequestAnimationFrame||k;var A=(new Date).getTime(),ha=g.cancelAnimationFrame||g.webkitCancelAnimationFrame||g.clearTimeout;bb=function(k){ha.call(g,k)}})(window);(function(){function g(g){for(var l=0,z=k.length;l<
z;l++){var r=k[l]?k[l]+g.charAt(0).toUpperCase()+g.slice(1):g;if(null!=A.style[r])return r}}var k=["","webkit","moz","ms","o"],A=document.createElement("div");O=g("transform");ka=g("perspective")?"translateZ(0) ":""})();M.Sly=ma;k.fn.sly=function(g,n){var A,z;if(!k.isPlainObject(g)){if("string"===la(g)||!1===g)A=!1===g?"destroy":g,z=Array.prototype.slice.call(arguments,1);g={}}return this.each(function(l,F){var r=k.data(F,"sly");r||A?r&&A&&r[A]&&r[A].apply(r,z):k.data(F,"sly",(new ma(F,g,n)).init())})};
ma.defaults={horizontal:!1,itemNav:null,itemSelector:null,smart:!1,activateOn:null,activateMiddle:!1,scrollSource:null,scrollBy:0,scrollHijack:300,scrollTrap:!1,dragSource:null,mouseDragging:!1,touchDragging:!1,releaseSwing:!1,swingSpeed:.2,elasticBounds:!1,interactive:null,scrollBar:null,dragHandle:!1,dynamicHandle:!1,minHandleSize:50,clickBar:!1,syncSpeed:.5,pagesBar:null,activatePageOn:null,pageBuilder:function(g){return"<li>"+(g+1)+"</li>"},forward:null,backward:null,prev:null,next:null,prevPage:null,
nextPage:null,cycleBy:null,cycleInterval:5E3,pauseOnHover:!1,startPaused:!1,moveBy:300,speed:0,easing:"swing",startAt:0,keyboardNavBy:null,draggedClass:"dragged",activeClass:"active",disabledClass:"disabled"}})(jQuery,window);